#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';
require __DIR__.'/config/bootstrap.php';

use App\Command\CheckRebootCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new CheckRebootCommand());

$application->run();
